// Package swag GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package swag

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "German Generalov",
            "url": "http://github.com/restlesswhy"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/currencies/price": {
            "get": {
                "description": "send currency symbol, get info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Currency"
                ],
                "summary": "Get all quotas of currencies",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Currency identificator",
                        "name": "symbol",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.QuotaDetailResponce"
                            }
                        }
                    }
                }
            }
        },
        "/currency": {
            "get": {
                "description": "send currency symbol, get info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Currency"
                ],
                "summary": "Get currency info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Currency identificator",
                        "name": "symbol",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Currency"
                        }
                    }
                }
            }
        },
        "/currency/price": {
            "get": {
                "description": "send currency symbol, get currency quota",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Currency"
                ],
                "summary": "Get currency quota",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Currency identificator",
                        "name": "symbol",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.QuotaDetailResponce"
                        }
                    }
                }
            }
        },
        "/currency/price/history": {
            "get": {
                "description": "send currency symbol, get info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Currency"
                ],
                "summary": "Get currency quota history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Currency identificator",
                        "name": "symbol",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.QuotaDetailResponce"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Currency": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "en_name": {
                    "type": "string"
                },
                "ru_name": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "models.QuotaDetailResponce": {
            "type": "object",
            "properties": {
                "buy": {
                    "type": "number"
                },
                "sell": {
                    "type": "number"
                },
                "symbol": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:4000",
	BasePath:         "/api/v1/",
	Schemes:          []string{"http"},
	Title:            "BTC-sercive swagger API",
	Description:      "BTC service with Hyperledger Fabric implementation.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
